version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    depends_on:
      - db
    env_file:
      - .env

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    command: ["npx", "prisma", "studio"]
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5555:5555"

volumes:
  db_data:
