# Use the official Node.js 20-alpine image as a base
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies
RUN npm ci

# Copy the Prisma schema file
COPY prisma/schema.prisma ./prisma/

# Set the command to run the migrations
CMD ["npx", "prisma", "migrate", "deploy"]
